"""empty message

Revision ID: 737eca42911c
Revises: 350b082c26d5
Create Date: 2022-07-29 17:46:53.228184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737eca42911c'
down_revision = '350b082c26d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['phone'])
    op.create_unique_constraint(None, 'Artist', ['facebook_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
